name: Maven Release


on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Import GPG Key
        run: |
          mkdir -p ~/.gnupg/
          printf "$MAVEN_SIGNING_KEY" > ~/.gnupg/maven-signing-key.asc
          gpg --import ~/.gnupg/maven-signing-key.asc
        env:
          MAVEN_SIGNING_KEY: ${{ secrets.MAVEN_SIGNING_KEY }}
      - name: Maven Deploy
        run: mvn -B -V deploy -Ddeploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
